### PR TITLE
Feature/make input format optional

### PR DESCRIPTION
**Pull request by CAMOBAP**
### Metanorma PR checklist

 - YES Breaking changes (list related PRs)
 - NO Documentation update required ([create task for this](https://github.com/metanorma/metanorma.org/issues/new))
 - NO External dependency introduced ([documentation update need](https://github.com/metanorma/metanorma.org/issues/new))
 - NO Gem with native library introduced

### Related PRs

 - https://github.com/metanorma/metanorma-iso/pull/557
 - https://github.com/metanorma/metanorma-cli/pull/262

### CODE REVIEW

**Review by ronaldtse — APPROVED** [review]

**Comment by ronaldtse** [comment]
We should add tests and a validation step for RFC XML (as an input format) as well, in a new issue.

**Comment by CAMOBAP** [comment]
@ronaldtse this PR should be released as major change (because breaking change)

But we have automatic release after downstream update here https://github.com/metanorma/mnconvert-ruby/blob/main/.github/workflows/release-tag.yml

To be honest, IDK how to handle this except removing `release-tag` workflow

Ideally, we should have here some tool for git log analyzing and next version suggestion like https://github.com/semantic-release/semantic-release. Unfortunatelly this tool is node-based, I would not like to drag node stuff into ruby repo. Also I wasn't able to find similar ruby tool yet

**Comment by ronaldtse** [comment]
@CAMOBAP I wouldn't consider this change a breaking change -- it does not break any existing functionality. Is there anything I'm missing?

**Comment by ronaldtse** [comment]
Oh you mean this change:

```ruby
  def self.convert(input_file, output_file, input_format, opts = {})
     validate(opts, input_format)
```
to
```
   def self.convert(input_file, output_file, opts = {})
     validate(opts)
```

Yes it is breaking.

**Comment by ronaldtse** [comment]
Thanks @camobap!

**Comment by CAMOBAP** [comment]
@ronaldtse @Intelligent2013 still open question about next release version of this gem, I think make sense to switch to manual release workflow here, how do you think?

**Comment by ronaldtse** [comment]
Agree.

**Comment by CAMOBAP** [comment]
@ronaldtse I have an idea, we can automatically report a ticket to this repo, once new mnconvert.jar is released, how do you think?

**Pull request merged**
