### PR TITLE
#15 do ci tests on proper IEEE input

### PR DESCRIPTION
**Pull request by CAMOBAP**
- #15

### CODE REVIEW

**Comment by CAMOBAP** [comment]
@Intelligent2013 I think I need your help, we are changed input XML from the one which was before to IEEE one (form mn-samples-ieee). And tests failed with validation errors

**Comment by Intelligent2013** [comment]
@CAMOBAP I've released mnconvert v1.25.0, but error occurs in
https://github.com/metanorma/mnconvert-ruby/actions/runs/3119518068/jobs/5059529835
```
SystemId Unknown; Line #575; Column #17; DEBUG: processing time 923 msec.
       Validate XML against DTD /home/runner/work/mnconvert-ruby/mnconvert-ruby/spec/../ieee-stl/standards-1-7-DTD/standards-1-7-dtd/standards.dtd...
       /tmp/rspec-20220924-2413-1e397tc/rice-en.cd.ieee.xml is NOT valid reason:
Error: [ERROR] Validation error: java.io.FileNotFoundException: /home/runner/work/mnconvert-ruby/mnconvert-ruby/spec/../ieee-stl/standards-1-7-DTD/standards-1-7-dtd/standards.dtd (No such file or directory)
```
I don't figure out why it can't find IEEE dtd now....

**Comment by CAMOBAP** [comment]
@Intelligent2013 thanks fothe r feedback, I have fixed this issue in this PR. Because we run tests on tag/release workflows we need to download/generate IEEE test assets on those workflows too

**Comment by Intelligent2013** [comment]
@CAMOBAP FYI, the validation issues fixed in mnconvert v1.25.0, but due the missing DTD issue, the mnconvert jar didn't updated in this repository in the action https://github.com/metanorma/mnconvert-ruby/actions/runs/3119518068. But I don't know how to re-run this action.... Therefore we have the validation errors until now:
```
Validate XML against DTD /home/runner/work/mnconvert-ruby/mnconvert-ruby/spec/../ieee/stl/standards-1-7-DTD/standards-1-7-dtd/standards.dtd...
       /tmp/rspec-20220924-1[85](https://github.com/metanorma/mnconvert-ruby/actions/runs/3119661680/jobs/5059786176#step:6:86)4-uuldjv/p987.6.xml is NOT valid reason:
Error: [ERROR] org.xml.sax.SAXParseException; lineNumber: 1024; columnNumber: 25; Element type "related" must be declared.
Error: [ERROR] org.xml.sax.SAXParseException; lineNumber: 1025; columnNumber: 12; Element type "preferred" must be declared.
Error: [ERROR] org.xml.sax.SAXParseException; lineNumber: 1028; columnNumber: 25; Element type "related" must be declared.
Error: [ERROR] org.xml.sax.SAXParseException; lineNumber: 1029; columnNumber: 12; Element type "preferred" must be declared.
```
even after your today's update.
So, please re-rerun this action if you can or tell me what should I do in the mnconvert repository.

**Comment by CAMOBAP** [comment]
> @CAMOBAP FYI, the validation issues fixed in mnconvert v1.25.0, but due the missing DTD issue, the mnconvert jar didn't updated in this repository in the action https://github.com/metanorma/mnconvert-ruby/actions/runs/3119518068. But I don't know how to re-run this action.... Therefore we have the validation errors until now:
> ```
> Validate XML against DTD /home/runner/work/mnconvert-ruby/mnconvert-ruby/spec/../ieee/stl/standards-1-7-DTD/standards-1-7-dtd/standards.dtd...
>        /tmp/rspec-20220924-1[85](https://github.com/metanorma/mnconvert-ruby/actions/runs/3119661680/jobs/5059786176#step:6:86)4-uuldjv/p987.6.xml is NOT valid reason:
> Error: [ERROR] org.xml.sax.SAXParseException; lineNumber: 1024; columnNumber: 25; Element type "related" must be declared.
> Error: [ERROR] org.xml.sax.SAXParseException; lineNumber: 1025; columnNumber: 12; Element type "preferred" must be declared.
> Error: [ERROR] org.xml.sax.SAXParseException; lineNumber: 1028; columnNumber: 25; Element type "related" must be declared.
> Error: [ERROR] org.xml.sax.SAXParseException; lineNumber: 1029; columnNumber: 12; Element type "preferred" must be declared.
> ```
> even after your today's update.
> So, please re-rerun this action if you can or tell me what should I do in the mnconvert repository.
> 

Thanks for reply, I will rerun today

**Comment by CAMOBAP** [comment]
@Intelligent2013 thanks, just confirmed that release 1.25.0 is passed

**Comment by Intelligent2013** [comment]
@CAMOBAP thanks!

**Comment by ronaldtse** [comment]
Thanks @CAMOBAP !

**Pull request merged**
